CREATE TABLE IF NOT EXISTS users (
	      id SERIAL PRIMARY KEY,
	      username VARCHAR(255) UNIQUE NOT NULL,
		  email VARCHAR(255) UNIQUE NOT NULL,
	      password VARCHAR(255) NOT NULL
	   );
	   
CREATE TABLE IF NOT EXISTS roles (
          id SERIAL PRIMARY KEY,
          name VARCHAR(50) UNIQUE NOT NULL
      );

CREATE TABLE IF NOT EXISTS permissions (
	      id SERIAL PRIMARY KEY,
		  name VARCHAR(50) UNIQUE NOT NULL
	  );